version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile

    container_name: bookrental

    ports:
      - "8081:8081"

    depends_on:
      - mysql_service

    # Avoids having to download all dependencies every time
    volumes:
      - ~/.m2:/root/.m2

    working_dir: /app

    command: mvn -f ./pom.xml clean spring-boot:run

    networks:
      - bookshelf_microservice-net
      - internal


  mysql_service:
    image: mysql:8

    container_name: books_rental_mysql_db

    restart: always

    environment:
      MYSQL_DATABASE: 'rentalsdb'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'

    ports:
      - "3306"

    volumes:
      - books_rental_db:/var/lib/mysql

    networks:
      - internal

volumes:
  books_rental_db:

networks:
  bookshelf_microservice-net:
    external: true
  internal:
    driver: bridge